# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeObjeto', models.CharField(max_length=100)),
                ('localEncontrado', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('categoria', models.CharField(choices=[('CELULAR', 'CELULAR'), ('CADERNO', 'CADERNO'), ('CALCULADORA', 'CALCULADORA')], max_length=100, null=True)),
                ('faculdade', models.CharField(choices=[('UNB', 'UNB'), ('CATOLICA', 'CATOLICA')], max_length=100)),
                ('descricao', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('retirado', models.CharField(choices=[('S', 'S'), ('N', 'N')], max_length=1)),
                ('nomePessoaRetirado', models.CharField(max_length=100, null=True)),
                ('identidade', models.CharField(max_length=20, null=True)),
                ('telefoneContato', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
